from datetime import datetime, timedelta
from models import db, GRCItem, Policy, Acknowledgment, Incident

GRC_SEED = [
    dict(category="Governance", subcategory="Policy Management",
         grc_item="Data Privacy Policy v2.1",
         description="Formal policy defining how personal data is collected, used, stored, and protected across the organization.",
         objective="Ensure all data handling practices comply with GDPR and CCPA.",
         owner="Legal Dept.", status="Implemented", due_date="2026-01-15",
         implementation_steps="Draft policy; Legal review; Executive sign-off; Publish to intranet; Employee acknowledgement campaign.",
         testing_method="Annual policy audit; spot-check acknowledgements; review against regulatory changes.",
         risk_level="Medium",
         mitigation_strategy="Mandatory annual refresher training; automated acknowledgement tracking.",
         compliance_standard="GDPR, CCPA",
         mock_data_example="Policy acknowledgement rate: 98.4% (1,240 of 1,260 employees).",
         notes="Next full review scheduled 2027-01-15."),
    dict(category="Governance", subcategory="Policy Management",
         grc_item="Acceptable Use Policy",
         description="Defines permitted and prohibited use of corporate IT systems, devices, and networks.",
         objective="Reduce insider risk and misuse of corporate assets.",
         owner="IT Security", status="Reviewed", due_date="2026-03-01",
         implementation_steps="Draft/update policy; align with HR handbook; distribute via LMS; require e-signature.",
         testing_method="Quarterly sampling of signed acknowledgements; helpdesk violation review.",
         risk_level="Low",
         mitigation_strategy="Automated LMS reminders; disciplinary process for repeat violations.",
         compliance_standard="ISO 27001 A.5.10",
         mock_data_example="Q1 2026: 3 minor violations logged, all remediated with coaching.",
         notes="Owner: IT Security Manager."),
    dict(category="Governance", subcategory="Ethics & Code of Conduct",
         grc_item="Code of Conduct Attestation Program",
         description="Annual program requiring employees to read and attest to the Code of Conduct, including anti-bribery provisions.",
         objective="Reinforce ethical culture and reduce legal/reputational exposure.",
         owner="HR / Compliance", status="Implemented", due_date="2026-01-31",
         implementation_steps="Update code content; deploy via LMS; track completion; escalate non-completers.",
         testing_method="Completion-rate dashboard; whistleblower hotline trend analysis.",
         risk_level="Medium",
         mitigation_strategy="Manager escalation workflow; Ethics Committee case review.",
         compliance_standard="FCPA, UK Bribery Act",
         mock_data_example="2026 cycle: 99.1% completion; 2 conflict-of-interest disclosures filed.",
         notes="Ethics Committee meets bi-monthly."),
    dict(category="Governance", subcategory="IT Governance",
         grc_item="IT Steering Committee Charter",
         description="Charter establishing the mandate, membership, and cadence of the IT Steering Committee.",
         objective="Align IT investment and risk decisions with business strategy.",
         owner="CIO", status="Implemented", due_date="2025-11-01",
         implementation_steps="Draft charter; obtain sponsorship; publish cadence; define voting rules.",
         testing_method="Annual charter review; attendance and decision-log audit.",
         risk_level="Low",
         mitigation_strategy="Defined quorum rules; escalation to CEO for stalled decisions.",
         compliance_standard="COBIT 2019",
         mock_data_example="Committee met 11 of 12 scheduled months in 2025.",
         notes="Charter renewal due Nov 2026."),
    dict(category="Risk Management", subcategory="Threat Assessment",
         grc_item="Phishing Susceptibility Program",
         description="Ongoing simulated phishing campaigns to measure and reduce employee susceptibility to social engineering.",
         objective="Quantify and reduce the risk posed by phishing attacks.",
         owner="IT Security", status="In Progress", due_date="2026-08-31",
         implementation_steps="Run monthly simulated phishing campaigns; analyze rates; target repeat clickers.",
         testing_method="Click-through and report-rate trending.",
         risk_level="High",
         mitigation_strategy="Mandatory remedial training; email filtering; MFA enforcement.",
         compliance_standard="ISO 27001 A.6.3",
         mock_data_example="June 2026: 8.2% click-through (down from 15% in Jan).",
         notes="Continue monthly cadence."),
    dict(category="Risk Management", subcategory="Incident Response",
         grc_item="Security Incident Response Plan",
         description="Documented procedures for detecting, containing, eradicating, and recovering from security incidents.",
         objective="Minimize impact and recovery time for security incidents.",
         owner="SOC Team", status="Implemented", due_date="2025-12-01",
         implementation_steps="Define response phases; assign IR roles; build templates; conduct tabletop exercises.",
         testing_method="Semi-annual tabletop exercises; post-incident review reports.",
         risk_level="Critical",
         mitigation_strategy="24/7 SOC monitoring; automated containment playbooks.",
         compliance_standard="NIST 800-61, ISO 27001 A.5.24",
         mock_data_example="Incident #IR-2026-014 contained in 47 minutes; no data exfiltration.",
         notes="Tabletop exercise scheduled for Q3 2026."),
    dict(category="Risk Management", subcategory="Business Continuity",
         grc_item="Business Continuity & Disaster Recovery Plan",
         description="Plan defining recovery time/point objectives and procedures to restore operations after disruption.",
         objective="Ensure continuity of critical business functions.",
         owner="Business Continuity Mgr.", status="In Progress", due_date="2026-10-15",
         implementation_steps="Update business impact analysis; define RTO/RPO; test failover.",
         testing_method="Annual full-scale DR test; quarterly tabletop walkthroughs.",
         risk_level="High",
         mitigation_strategy="Redundant data center failover; documented manual workarounds.",
         compliance_standard="ISO 22301",
         mock_data_example="2025 DR test: failover completed in 3.5 hours against 4-hour RTO.",
         notes="2026 full-scale test planned for October."),
    dict(category="Risk Management", subcategory="Third-Party Risk",
         grc_item="Third-Party Risk Assessment Program",
         description="Risk-based due diligence and monitoring program for vendors handling sensitive data.",
         objective="Reduce risk introduced through third-party relationships.",
         owner="Vendor Risk Mgmt.", status="In Progress", due_date="2026-06-30",
         implementation_steps="Send questionnaires; review certifications; conduct reassessments.",
         testing_method="Annual reassessment for Critical/High tier vendors.",
         risk_level="High",
         mitigation_strategy="Contractual security requirements; continuous monitoring service.",
         compliance_standard="NIST 800-161, SIG Questionnaire",
         mock_data_example="38 Critical-tier vendors assessed; 6 flagged for remediation.",
         notes="Remediation deadline 2026-07-31."),
    dict(category="Compliance", subcategory="Regulatory Adherence",
         grc_item="SOC 2 Type II Audit",
         description="Independent audit assessing controls over security, availability, and confidentiality.",
         objective="Achieve and maintain SOC 2 Type II attestation.",
         owner="CISO", status="In Progress", due_date="2026-12-31",
         implementation_steps="Perform gap analysis; remediate gaps; compile evidence; engage auditor.",
         testing_method="Successful completion of SOC 2 Type II report.",
         risk_level="Critical",
         mitigation_strategy="Continuous control monitoring platform.",
         compliance_standard="AICPA SOC 2 Trust Services Criteria",
         mock_data_example="Interim review found 1 minor deficiency in access recertification.",
         notes="Field work begins Q4 2026."),
    dict(category="Compliance", subcategory="Regulatory Adherence",
         grc_item="GDPR Compliance Program",
         description="Ongoing program ensuring lawful processing of EU personal data.",
         objective="Maintain full compliance with GDPR obligations.",
         owner="DPO", status="Implemented", due_date="2026-01-01",
         implementation_steps="Maintain records of processing; conduct DPIAs; operate DSAR portal.",
         testing_method="Annual GDPR compliance audit; DSAR response-time tracking.",
         risk_level="High",
         mitigation_strategy="DPIA required before new processing; 30-day DSAR SLA.",
         compliance_standard="GDPR",
         mock_data_example="Q2 2026: 34 DSARs received, average response time 11 days.",
         notes="EU representative appointed per Art. 27."),
    dict(category="Compliance", subcategory="Data Retention",
         grc_item="Data Retention & Disposal Policy",
         description="Policy and automated process governing how long records are kept and disposed of.",
         objective="Comply with legal/regulatory retention requirements.",
         owner="Data Governance", status="Implemented", due_date="2026-02-28",
         implementation_steps="Define retention schedules; automate archival/deletion; audit logs.",
         testing_method="Monthly audit of deletion logs against schedule.",
         risk_level="Medium",
         mitigation_strategy="Automated deletion workflows; legal hold override process.",
         compliance_standard="CCPA, internal records policy",
         mock_data_example="April 2026: 12,400 records past retention securely deleted.",
         notes="Legal hold list reviewed monthly."),
    dict(category="Compliance", subcategory="Regulatory Adherence",
         grc_item="PCI DSS Compliance",
         description="Compliance program ensuring secure handling of cardholder data.",
         objective="Maintain PCI DSS compliance to safely process card payments.",
         owner="IT Security / Finance", status="Reviewed", due_date="2026-05-01",
         implementation_steps="Complete SAQ/ROC; segment cardholder data environment; conduct ASV scans.",
         testing_method="Quarterly ASV scans; annual penetration test.",
         risk_level="Critical",
         mitigation_strategy="Network segmentation; tokenization of stored card data.",
         compliance_standard="PCI DSS v4.0",
         mock_data_example="Q1 2026 ASV scan passed with 0 critical findings.",
         notes="Merchant level: Level 2; SAQ D in progress."),
]

POLICY_SEED = [
    dict(name="Data Privacy Policy v2.1", category="Governance",
         description="Governs how personal data is collected, used, stored, and protected.",
         version="2.1", effective_date="2026-01-15"),
    dict(name="Acceptable Use Policy", category="Governance",
         description="Defines permitted and prohibited use of corporate IT systems and devices.",
         version="1.3", effective_date="2026-03-01"),
    dict(name="Code of Conduct", category="Governance",
         description="Corporate ethics standards, including anti-bribery and conflict-of-interest rules.",
         version="4.0", effective_date="2026-01-01"),
    dict(name="Security & Privacy Awareness Training Policy", category="Compliance",
         description="Mandatory annual training requirement covering security and privacy practices.",
         version="2.0", effective_date="2026-01-31"),
]

INCIDENT_SEED = [
    dict(title="Unauthorized Access Attempt - Production DB",
         description="SOC detected an anomalous login attempt against the production customer database from an unrecognized IP range.",
         severity="Critical", status="Contained", reported_by="SOC Analyst - J. Rivera",
         days_ago=12, resolved_days_ago=12),
    dict(title="Phishing Email Reported by Finance Team",
         description="Employee reported a suspicious invoice email impersonating a known vendor requesting a wire transfer change.",
         severity="High", status="Resolved", reported_by="A. Chen (Finance)",
         days_ago=30, resolved_days_ago=29),
    dict(title="Unpatched Server Detected in Vulnerability Scan",
         description="Routine vulnerability scan flagged a production web server missing a critical kernel security patch.",
         severity="Medium", status="Investigating", reported_by="Automated Scanner",
         days_ago=3, resolved_days_ago=None),
]


def seed_if_empty():
    if GRCItem.query.first() is None:
        for item in GRC_SEED:
            db.session.add(GRCItem(**item))

    if Policy.query.first() is None:
        policies = []
        for p in POLICY_SEED:
            policy = Policy(**p)
            db.session.add(policy)
            policies.append(policy)
        db.session.flush()  # get policy IDs

        sample_employees = ["J. Martinez", "A. Chen", "S. Okafor", "T. Nguyen", "R. Patel"]
        for policy in policies:
            for name in sample_employees[: 3]:
                db.session.add(Acknowledgment(policy_id=policy.id, employee_name=name))

    if Incident.query.first() is None:
        now = datetime.utcnow()
        for inc in INCIDENT_SEED:
            resolved_at = None
            if inc["resolved_days_ago"] is not None:
                resolved_at = now - timedelta(days=inc["resolved_days_ago"])
            db.session.add(Incident(
                title=inc["title"], description=inc["description"],
                severity=inc["severity"], status=inc["status"],
                reported_by=inc["reported_by"],
                reported_at=now - timedelta(days=inc["days_ago"]),
                resolved_at=resolved_at,
            ))

    db.session.commit()
