# Auto-generated lab content — edit freely.
LAB = {'lab_number': '02',
 'title': 'Understanding Risk and Risk Management',
 'eyebrow': 'Foundations · Risk',
 'exercise_type': 'risk_register',
 'topic_intro': 'Risk management turns vague worry into a prioritized, defensible list: what could go wrong, '
                'how likely is it, how bad would it be, and what are we doing about it. Build a risk '
                'register below — rate likelihood and impact (1–5) for each risk and choose a treatment.',
 'key_points': ["Risk score = Likelihood × Impact. It's a prioritization tool, not a precise prediction.",
                'Treatment options: Accept (live with it), Mitigate (reduce it), Transfer '
                '(insurance/contract), Avoid (stop the activity).',
                "A risk register is only useful if it's revisited — a one-time exercise goes stale within a "
                'quarter.'],
 'scenarios': {'finance': {'regulator': 'SAMA Cyber Security Framework · Banking / Finance Sector',
                           'name': 'Finance Department — SAMA-Regulated Bank',
                           'context': 'Build the initial cyber risk register for the finance department of a '
                                      'SAMA-regulated bank.',
                           'entries': [{'id': 'R1',
                                        'label': 'Core banking system unavailable during peak hours',
                                        'desc': 'Outage of the core banking platform affecting customer '
                                                'transactions.',
                                        'likelihood': 2,
                                        'impact': 5,
                                        'treatment': 'Mitigate'},
                                       {'id': 'R2',
                                        'label': 'Unauthorized internal access to customer financial records',
                                        'desc': "An employee accesses account data outside their role's "
                                                'need-to-know.',
                                        'likelihood': 3,
                                        'impact': 4,
                                        'treatment': 'Mitigate'},
                                       {'id': 'R3',
                                        'label': 'Third-party payment processor breach',
                                        'desc': 'A vendor holding card or payment data is compromised.',
                                        'likelihood': 3,
                                        'impact': 5,
                                        'treatment': 'Transfer'},
                                       {'id': 'R4',
                                        'label': 'Phishing leading to fraudulent wire transfer',
                                        'desc': 'Social engineering tricks finance staff into authorizing a '
                                                'fraudulent payment.',
                                        'likelihood': 4,
                                        'impact': 4,
                                        'treatment': 'Mitigate'},
                                       {'id': 'R5',
                                        'label': 'Regulatory reporting deadline missed after incident',
                                        'desc': 'SAMA incident-notification timelines are missed due to '
                                                'unclear escalation paths.',
                                        'likelihood': 2,
                                        'impact': 3,
                                        'treatment': 'Mitigate'},
                                       {'id': 'R6',
                                        'label': 'Legacy system without vendor security patches',
                                        'desc': 'An end-of-life system continues processing financial data '
                                                'without current patching.',
                                        'likelihood': 3,
                                        'impact': 3,
                                        'treatment': 'Mitigate'}]},
               'software': {'regulator': 'NCA ECC · PDPL (SDAIA) · Software / SaaS Sector',
                            'name': 'Product & Engineering — Saudi SaaS Company',
                            'context': 'Build the initial cyber risk register for a Saudi SaaS company '
                                       'handling customer personal data under PDPL.',
                            'entries': [{'id': 'R1',
                                         'label': 'Misconfigured cloud storage bucket exposes customer data',
                                         'desc': 'A storage bucket is left publicly accessible due to a '
                                                 'misconfiguration.',
                                         'likelihood': 3,
                                         'impact': 5,
                                         'treatment': 'Mitigate'},
                                        {'id': 'R2',
                                         'label': 'Compromised CI/CD pipeline injects malicious code',
                                         'desc': 'An attacker gains access to the build pipeline and ships '
                                                 'tampered code.',
                                         'likelihood': 2,
                                         'impact': 5,
                                         'treatment': 'Mitigate'},
                                        {'id': 'R3',
                                         'label': 'Third-party API dependency has a critical vulnerability',
                                         'desc': 'A library or service the product depends on discloses a '
                                                 'critical CVE.',
                                         'likelihood': 4,
                                         'impact': 3,
                                         'treatment': 'Mitigate'},
                                        {'id': 'R4',
                                         'label': 'Employee offboarding leaves access active',
                                         'desc': "A departed employee's credentials or API keys remain valid "
                                                 'after termination.',
                                         'likelihood': 3,
                                         'impact': 3,
                                         'treatment': 'Mitigate'},
                                        {'id': 'R5',
                                         'label': 'PDPL cross-border data transfer without safeguards',
                                         'desc': 'Customer personal data is processed outside KSA without '
                                                 'the required legal basis.',
                                         'likelihood': 2,
                                         'impact': 4,
                                         'treatment': 'Avoid'},
                                        {'id': 'R6',
                                         'label': 'Customer data commingled in shared multi-tenant database',
                                         'desc': "A bug in tenant isolation exposes one customer's data to "
                                                 'another.',
                                         'likelihood': 2,
                                         'impact': 5,
                                         'treatment': 'Mitigate'}]}}}
